//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FORMATTEDNUMBER_NoID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FORMATTEDNUMBER_NoID">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FormatInteger"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FormatCurrencyAmt"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FormatModFactor"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FormatPct"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FormatText"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FORMATTEDNUMBER_NoID", propOrder = {
    "formatInteger",
    "formatCurrencyAmt",
    "formatModFactor",
    "formatPct",
    "formatText"
})
public class FORMATTEDNUMBERNoID {

    @XmlElement(name = "FormatInteger")
    protected Long formatInteger;
    @XmlElement(name = "FormatCurrencyAmt")
    protected CURRENCY formatCurrencyAmt;
    @XmlElement(name = "FormatModFactor")
    protected Decimal formatModFactor;
    @XmlElement(name = "FormatPct")
    protected PercentDecimal formatPct;
    @XmlElement(name = "FormatText")
    protected C50 formatText;

    /**
     * Gets the value of the formatInteger property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFormatInteger() {
        return formatInteger;
    }

    /**
     * Sets the value of the formatInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFormatInteger(Long value) {
        this.formatInteger = value;
    }

    /**
     * Gets the value of the formatCurrencyAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getFormatCurrencyAmt() {
        return formatCurrencyAmt;
    }

    /**
     * Sets the value of the formatCurrencyAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setFormatCurrencyAmt(CURRENCY value) {
        this.formatCurrencyAmt = value;
    }

    /**
     * Gets the value of the formatModFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Decimal }
     *     
     */
    public Decimal getFormatModFactor() {
        return formatModFactor;
    }

    /**
     * Sets the value of the formatModFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decimal }
     *     
     */
    public void setFormatModFactor(Decimal value) {
        this.formatModFactor = value;
    }

    /**
     * Gets the value of the formatPct property.
     * 
     * @return
     *     possible object is
     *     {@link PercentDecimal }
     *     
     */
    public PercentDecimal getFormatPct() {
        return formatPct;
    }

    /**
     * Sets the value of the formatPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentDecimal }
     *     
     */
    public void setFormatPct(PercentDecimal value) {
        this.formatPct = value;
    }

    /**
     * Gets the value of the formatText property.
     * 
     * @return
     *     possible object is
     *     {@link C50 }
     *     
     */
    public C50 getFormatText() {
        return formatText;
    }

    /**
     * Sets the value of the formatText property.
     * 
     * @param value
     *     allowed object is
     *     {@link C50 }
     *     
     */
    public void setFormatText(C50 value) {
        this.formatText = value;
    }

}
