//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneralLiabilityLineBusiness_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralLiabilityLineBusiness_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PCLINEBUSINESS">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LiabilityInfo"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ProductCompletedOpsInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}StateSupplementInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}QuestionAnswer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralLiabilityLineBusiness_Type", propOrder = {
    "liabilityInfo",
    "productCompletedOpsInfo",
    "stateSupplementInfo",
    "questionAnswer"
})
public class GeneralLiabilityLineBusinessType
    extends PCLINEBUSINESS
{

    @XmlElement(name = "LiabilityInfo", required = true)
    protected LiabilityInfoType liabilityInfo;
    @XmlElement(name = "ProductCompletedOpsInfo")
    protected List<ProductCompletedOpsInfoType> productCompletedOpsInfo;
    @XmlElement(name = "StateSupplementInfo")
    protected List<StateSupplementInfoType> stateSupplementInfo;
    @XmlElement(name = "QuestionAnswer")
    protected List<QuestionAnswerType> questionAnswer;

    /**
     * Gets the value of the liabilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LiabilityInfoType }
     *     
     */
    public LiabilityInfoType getLiabilityInfo() {
        return liabilityInfo;
    }

    /**
     * Sets the value of the liabilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiabilityInfoType }
     *     
     */
    public void setLiabilityInfo(LiabilityInfoType value) {
        this.liabilityInfo = value;
    }

    /**
     * Gets the value of the productCompletedOpsInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productCompletedOpsInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductCompletedOpsInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductCompletedOpsInfoType }
     * 
     * 
     */
    public List<ProductCompletedOpsInfoType> getProductCompletedOpsInfo() {
        if (productCompletedOpsInfo == null) {
            productCompletedOpsInfo = new ArrayList<ProductCompletedOpsInfoType>();
        }
        return this.productCompletedOpsInfo;
    }

    /**
     * Gets the value of the stateSupplementInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateSupplementInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateSupplementInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StateSupplementInfoType }
     * 
     * 
     */
    public List<StateSupplementInfoType> getStateSupplementInfo() {
        if (stateSupplementInfo == null) {
            stateSupplementInfo = new ArrayList<StateSupplementInfoType>();
        }
        return this.stateSupplementInfo;
    }

    /**
     * Gets the value of the questionAnswer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questionAnswer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestionAnswer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuestionAnswerType }
     * 
     * 
     */
    public List<QuestionAnswerType> getQuestionAnswer() {
        if (questionAnswer == null) {
            questionAnswer = new ArrayList<QuestionAnswerType>();
        }
        return this.questionAnswer;
    }

}
