//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for GlassSignUnderwriting_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlassSignUnderwriting_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PaintedPlatesCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FixedGluedOrAngleSetPlatesInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ObstructionsOrUnusualSettingsInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}UnusualSettingsAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}InsuranceForTapeOnGlassInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}TapeAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}InsuranceForLetteringOnGlassInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LetteringAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}BldgOrAreaUnderConstructionInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}GlassOrSignsHaveDefectsInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AgentInspectInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PremisesVacantInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SignOffPremisesNotAttachedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AllExteriorAboveSecondFloorInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AllExteriorInsuredInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AnyGlassStructuralInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}GlassProtectedByMeshOrULGlazingInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AllInteriorGlassInsuredInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FactoryBuiltInsulatingGlassInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}BldgUseCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ScheduleTypeCd"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlassSignUnderwriting_Type", propOrder = {
    "paintedPlatesCd",
    "fixedGluedOrAngleSetPlatesInd",
    "obstructionsOrUnusualSettingsInd",
    "unusualSettingsAmt",
    "insuranceForTapeOnGlassInd",
    "tapeAmt",
    "insuranceForLetteringOnGlassInd",
    "letteringAmt",
    "bldgOrAreaUnderConstructionInd",
    "glassOrSignsHaveDefectsInd",
    "agentInspectInd",
    "premisesVacantInd",
    "signOffPremisesNotAttachedInd",
    "allExteriorAboveSecondFloorInd",
    "allExteriorInsuredInd",
    "anyGlassStructuralInd",
    "glassProtectedByMeshOrULGlazingInd",
    "allInteriorGlassInsuredInd",
    "factoryBuiltInsulatingGlassInd",
    "bldgUseCd",
    "scheduleTypeCd"
})
public class GlassSignUnderwritingType {

    @XmlElement(name = "PaintedPlatesCd")
    protected PaintedPlates paintedPlatesCd;
    @XmlElement(name = "FixedGluedOrAngleSetPlatesInd")
    protected Boolean fixedGluedOrAngleSetPlatesInd;
    @XmlElement(name = "ObstructionsOrUnusualSettingsInd")
    protected Boolean obstructionsOrUnusualSettingsInd;
    @XmlElement(name = "UnusualSettingsAmt")
    protected CURRENCY unusualSettingsAmt;
    @XmlElement(name = "InsuranceForTapeOnGlassInd")
    protected Boolean insuranceForTapeOnGlassInd;
    @XmlElement(name = "TapeAmt")
    protected CURRENCY tapeAmt;
    @XmlElement(name = "InsuranceForLetteringOnGlassInd")
    protected Boolean insuranceForLetteringOnGlassInd;
    @XmlElement(name = "LetteringAmt")
    protected CURRENCY letteringAmt;
    @XmlElement(name = "BldgOrAreaUnderConstructionInd")
    protected Boolean bldgOrAreaUnderConstructionInd;
    @XmlElement(name = "GlassOrSignsHaveDefectsInd")
    protected Boolean glassOrSignsHaveDefectsInd;
    @XmlElement(name = "AgentInspectInd")
    protected Boolean agentInspectInd;
    @XmlElement(name = "PremisesVacantInd")
    protected Boolean premisesVacantInd;
    @XmlElement(name = "SignOffPremisesNotAttachedInd")
    protected Boolean signOffPremisesNotAttachedInd;
    @XmlElement(name = "AllExteriorAboveSecondFloorInd")
    protected Boolean allExteriorAboveSecondFloorInd;
    @XmlElement(name = "AllExteriorInsuredInd")
    protected Boolean allExteriorInsuredInd;
    @XmlElement(name = "AnyGlassStructuralInd")
    protected Boolean anyGlassStructuralInd;
    @XmlElement(name = "GlassProtectedByMeshOrULGlazingInd")
    protected Boolean glassProtectedByMeshOrULGlazingInd;
    @XmlElement(name = "AllInteriorGlassInsuredInd")
    protected Boolean allInteriorGlassInsuredInd;
    @XmlElement(name = "FactoryBuiltInsulatingGlassInd")
    protected Boolean factoryBuiltInsulatingGlassInd;
    @XmlElement(name = "BldgUseCd")
    protected BuildingUse bldgUseCd;
    @XmlElement(name = "ScheduleTypeCd", required = true)
    protected ScheduleType scheduleTypeCd;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the paintedPlatesCd property.
     * 
     * @return
     *     possible object is
     *     {@link PaintedPlates }
     *     
     */
    public PaintedPlates getPaintedPlatesCd() {
        return paintedPlatesCd;
    }

    /**
     * Sets the value of the paintedPlatesCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaintedPlates }
     *     
     */
    public void setPaintedPlatesCd(PaintedPlates value) {
        this.paintedPlatesCd = value;
    }

    /**
     * Gets the value of the fixedGluedOrAngleSetPlatesInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFixedGluedOrAngleSetPlatesInd() {
        return fixedGluedOrAngleSetPlatesInd;
    }

    /**
     * Sets the value of the fixedGluedOrAngleSetPlatesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFixedGluedOrAngleSetPlatesInd(Boolean value) {
        this.fixedGluedOrAngleSetPlatesInd = value;
    }

    /**
     * Gets the value of the obstructionsOrUnusualSettingsInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getObstructionsOrUnusualSettingsInd() {
        return obstructionsOrUnusualSettingsInd;
    }

    /**
     * Sets the value of the obstructionsOrUnusualSettingsInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setObstructionsOrUnusualSettingsInd(Boolean value) {
        this.obstructionsOrUnusualSettingsInd = value;
    }

    /**
     * Gets the value of the unusualSettingsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getUnusualSettingsAmt() {
        return unusualSettingsAmt;
    }

    /**
     * Sets the value of the unusualSettingsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setUnusualSettingsAmt(CURRENCY value) {
        this.unusualSettingsAmt = value;
    }

    /**
     * Gets the value of the insuranceForTapeOnGlassInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInsuranceForTapeOnGlassInd() {
        return insuranceForTapeOnGlassInd;
    }

    /**
     * Sets the value of the insuranceForTapeOnGlassInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsuranceForTapeOnGlassInd(Boolean value) {
        this.insuranceForTapeOnGlassInd = value;
    }

    /**
     * Gets the value of the tapeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getTapeAmt() {
        return tapeAmt;
    }

    /**
     * Sets the value of the tapeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setTapeAmt(CURRENCY value) {
        this.tapeAmt = value;
    }

    /**
     * Gets the value of the insuranceForLetteringOnGlassInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInsuranceForLetteringOnGlassInd() {
        return insuranceForLetteringOnGlassInd;
    }

    /**
     * Sets the value of the insuranceForLetteringOnGlassInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsuranceForLetteringOnGlassInd(Boolean value) {
        this.insuranceForLetteringOnGlassInd = value;
    }

    /**
     * Gets the value of the letteringAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getLetteringAmt() {
        return letteringAmt;
    }

    /**
     * Sets the value of the letteringAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setLetteringAmt(CURRENCY value) {
        this.letteringAmt = value;
    }

    /**
     * Gets the value of the bldgOrAreaUnderConstructionInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getBldgOrAreaUnderConstructionInd() {
        return bldgOrAreaUnderConstructionInd;
    }

    /**
     * Sets the value of the bldgOrAreaUnderConstructionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBldgOrAreaUnderConstructionInd(Boolean value) {
        this.bldgOrAreaUnderConstructionInd = value;
    }

    /**
     * Gets the value of the glassOrSignsHaveDefectsInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getGlassOrSignsHaveDefectsInd() {
        return glassOrSignsHaveDefectsInd;
    }

    /**
     * Sets the value of the glassOrSignsHaveDefectsInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGlassOrSignsHaveDefectsInd(Boolean value) {
        this.glassOrSignsHaveDefectsInd = value;
    }

    /**
     * Gets the value of the agentInspectInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAgentInspectInd() {
        return agentInspectInd;
    }

    /**
     * Sets the value of the agentInspectInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAgentInspectInd(Boolean value) {
        this.agentInspectInd = value;
    }

    /**
     * Gets the value of the premisesVacantInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPremisesVacantInd() {
        return premisesVacantInd;
    }

    /**
     * Sets the value of the premisesVacantInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPremisesVacantInd(Boolean value) {
        this.premisesVacantInd = value;
    }

    /**
     * Gets the value of the signOffPremisesNotAttachedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSignOffPremisesNotAttachedInd() {
        return signOffPremisesNotAttachedInd;
    }

    /**
     * Sets the value of the signOffPremisesNotAttachedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSignOffPremisesNotAttachedInd(Boolean value) {
        this.signOffPremisesNotAttachedInd = value;
    }

    /**
     * Gets the value of the allExteriorAboveSecondFloorInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAllExteriorAboveSecondFloorInd() {
        return allExteriorAboveSecondFloorInd;
    }

    /**
     * Sets the value of the allExteriorAboveSecondFloorInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllExteriorAboveSecondFloorInd(Boolean value) {
        this.allExteriorAboveSecondFloorInd = value;
    }

    /**
     * Gets the value of the allExteriorInsuredInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAllExteriorInsuredInd() {
        return allExteriorInsuredInd;
    }

    /**
     * Sets the value of the allExteriorInsuredInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllExteriorInsuredInd(Boolean value) {
        this.allExteriorInsuredInd = value;
    }

    /**
     * Gets the value of the anyGlassStructuralInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAnyGlassStructuralInd() {
        return anyGlassStructuralInd;
    }

    /**
     * Sets the value of the anyGlassStructuralInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnyGlassStructuralInd(Boolean value) {
        this.anyGlassStructuralInd = value;
    }

    /**
     * Gets the value of the glassProtectedByMeshOrULGlazingInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getGlassProtectedByMeshOrULGlazingInd() {
        return glassProtectedByMeshOrULGlazingInd;
    }

    /**
     * Sets the value of the glassProtectedByMeshOrULGlazingInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGlassProtectedByMeshOrULGlazingInd(Boolean value) {
        this.glassProtectedByMeshOrULGlazingInd = value;
    }

    /**
     * Gets the value of the allInteriorGlassInsuredInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAllInteriorGlassInsuredInd() {
        return allInteriorGlassInsuredInd;
    }

    /**
     * Sets the value of the allInteriorGlassInsuredInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllInteriorGlassInsuredInd(Boolean value) {
        this.allInteriorGlassInsuredInd = value;
    }

    /**
     * Gets the value of the factoryBuiltInsulatingGlassInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFactoryBuiltInsulatingGlassInd() {
        return factoryBuiltInsulatingGlassInd;
    }

    /**
     * Sets the value of the factoryBuiltInsulatingGlassInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFactoryBuiltInsulatingGlassInd(Boolean value) {
        this.factoryBuiltInsulatingGlassInd = value;
    }

    /**
     * Gets the value of the bldgUseCd property.
     * 
     * @return
     *     possible object is
     *     {@link BuildingUse }
     *     
     */
    public BuildingUse getBldgUseCd() {
        return bldgUseCd;
    }

    /**
     * Sets the value of the bldgUseCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildingUse }
     *     
     */
    public void setBldgUseCd(BuildingUse value) {
        this.bldgUseCd = value;
    }

    /**
     * Gets the value of the scheduleTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleType }
     *     
     */
    public ScheduleType getScheduleTypeCd() {
        return scheduleTypeCd;
    }

    /**
     * Sets the value of the scheduleTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleType }
     *     
     */
    public void setScheduleTypeCd(ScheduleType value) {
        this.scheduleTypeCd = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
