//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for NonOwnedAircraft_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NonOwnedAircraft_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LoggedHours" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumPassengers" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PassengerTypeCd" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumBranchs" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumEmployees" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumPilotEmployees" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumEmployedPilots" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumEmployeesOwnAircraft" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumEmployeesTravel" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumEmployeesOwnAircraftUsed" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EmpOwnPrimaryLiabLimitAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumAircraft" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AircraftOwnedServiced" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}RentedAircraftLiabLimitAmt" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NonOwnedAircraft_Type", propOrder = {
    "loggedHours",
    "numPassengers",
    "passengerTypeCd",
    "numBranchs",
    "numEmployees",
    "numPilotEmployees",
    "numEmployedPilots",
    "numEmployeesOwnAircraft",
    "numEmployeesTravel",
    "numEmployeesOwnAircraftUsed",
    "empOwnPrimaryLiabLimitAmt",
    "numAircraft",
    "aircraftOwnedServiced",
    "rentedAircraftLiabLimitAmt"
})
public class NonOwnedAircraftType {

    @XmlElement(name = "LoggedHours")
    protected List<LoggedHoursType> loggedHours;
    @XmlElement(name = "NumPassengers")
    protected Long numPassengers;
    @XmlElement(name = "PassengerTypeCd")
    protected List<PassengerType> passengerTypeCd;
    @XmlElement(name = "NumBranchs")
    protected Long numBranchs;
    @XmlElement(name = "NumEmployees")
    protected Long numEmployees;
    @XmlElement(name = "NumPilotEmployees")
    protected Long numPilotEmployees;
    @XmlElement(name = "NumEmployedPilots")
    protected Long numEmployedPilots;
    @XmlElement(name = "NumEmployeesOwnAircraft")
    protected Long numEmployeesOwnAircraft;
    @XmlElement(name = "NumEmployeesTravel")
    protected Long numEmployeesTravel;
    @XmlElement(name = "NumEmployeesOwnAircraftUsed")
    protected Long numEmployeesOwnAircraftUsed;
    @XmlElement(name = "EmpOwnPrimaryLiabLimitAmt")
    protected CURRENCY empOwnPrimaryLiabLimitAmt;
    @XmlElement(name = "NumAircraft")
    protected Long numAircraft;
    @XmlElement(name = "AircraftOwnedServiced")
    protected AircraftOwnedServicedType aircraftOwnedServiced;
    @XmlElement(name = "RentedAircraftLiabLimitAmt")
    protected CURRENCY rentedAircraftLiabLimitAmt;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the loggedHours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loggedHours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoggedHours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoggedHoursType }
     * 
     * 
     */
    public List<LoggedHoursType> getLoggedHours() {
        if (loggedHours == null) {
            loggedHours = new ArrayList<LoggedHoursType>();
        }
        return this.loggedHours;
    }

    /**
     * Gets the value of the numPassengers property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumPassengers() {
        return numPassengers;
    }

    /**
     * Sets the value of the numPassengers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumPassengers(Long value) {
        this.numPassengers = value;
    }

    /**
     * Gets the value of the passengerTypeCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the passengerTypeCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPassengerTypeCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PassengerType }
     * 
     * 
     */
    public List<PassengerType> getPassengerTypeCd() {
        if (passengerTypeCd == null) {
            passengerTypeCd = new ArrayList<PassengerType>();
        }
        return this.passengerTypeCd;
    }

    /**
     * Gets the value of the numBranchs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumBranchs() {
        return numBranchs;
    }

    /**
     * Sets the value of the numBranchs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumBranchs(Long value) {
        this.numBranchs = value;
    }

    /**
     * Gets the value of the numEmployees property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumEmployees() {
        return numEmployees;
    }

    /**
     * Sets the value of the numEmployees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumEmployees(Long value) {
        this.numEmployees = value;
    }

    /**
     * Gets the value of the numPilotEmployees property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumPilotEmployees() {
        return numPilotEmployees;
    }

    /**
     * Sets the value of the numPilotEmployees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumPilotEmployees(Long value) {
        this.numPilotEmployees = value;
    }

    /**
     * Gets the value of the numEmployedPilots property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumEmployedPilots() {
        return numEmployedPilots;
    }

    /**
     * Sets the value of the numEmployedPilots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumEmployedPilots(Long value) {
        this.numEmployedPilots = value;
    }

    /**
     * Gets the value of the numEmployeesOwnAircraft property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumEmployeesOwnAircraft() {
        return numEmployeesOwnAircraft;
    }

    /**
     * Sets the value of the numEmployeesOwnAircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumEmployeesOwnAircraft(Long value) {
        this.numEmployeesOwnAircraft = value;
    }

    /**
     * Gets the value of the numEmployeesTravel property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumEmployeesTravel() {
        return numEmployeesTravel;
    }

    /**
     * Sets the value of the numEmployeesTravel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumEmployeesTravel(Long value) {
        this.numEmployeesTravel = value;
    }

    /**
     * Gets the value of the numEmployeesOwnAircraftUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumEmployeesOwnAircraftUsed() {
        return numEmployeesOwnAircraftUsed;
    }

    /**
     * Sets the value of the numEmployeesOwnAircraftUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumEmployeesOwnAircraftUsed(Long value) {
        this.numEmployeesOwnAircraftUsed = value;
    }

    /**
     * Gets the value of the empOwnPrimaryLiabLimitAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getEmpOwnPrimaryLiabLimitAmt() {
        return empOwnPrimaryLiabLimitAmt;
    }

    /**
     * Sets the value of the empOwnPrimaryLiabLimitAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setEmpOwnPrimaryLiabLimitAmt(CURRENCY value) {
        this.empOwnPrimaryLiabLimitAmt = value;
    }

    /**
     * Gets the value of the numAircraft property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumAircraft() {
        return numAircraft;
    }

    /**
     * Sets the value of the numAircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumAircraft(Long value) {
        this.numAircraft = value;
    }

    /**
     * Gets the value of the aircraftOwnedServiced property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftOwnedServicedType }
     *     
     */
    public AircraftOwnedServicedType getAircraftOwnedServiced() {
        return aircraftOwnedServiced;
    }

    /**
     * Sets the value of the aircraftOwnedServiced property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftOwnedServicedType }
     *     
     */
    public void setAircraftOwnedServiced(AircraftOwnedServicedType value) {
        this.aircraftOwnedServiced = value;
    }

    /**
     * Gets the value of the rentedAircraftLiabLimitAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getRentedAircraftLiabLimitAmt() {
        return rentedAircraftLiabLimitAmt;
    }

    /**
     * Sets the value of the rentedAircraftLiabLimitAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setRentedAircraftLiabLimitAmt(CURRENCY value) {
        this.rentedAircraftLiabLimitAmt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
