//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TowerAntennaInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TowerAntennaInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}YearBuilt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ErectedDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DesignTypeCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}MaxWindSpeed" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DeIcingEquipmentInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ElectricalProtectionCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}TowerOnBldgInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}TowerAntennaExposureInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AlterationsDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}MaintenanceProgramDesc" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *       &lt;attribute name="TowerErectorRef" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TowerAntennaInfo_Type", propOrder = {
    "yearBuilt",
    "erectedDt",
    "designTypeCd",
    "maxWindSpeed",
    "deIcingEquipmentInd",
    "electricalProtectionCd",
    "towerOnBldgInd",
    "towerAntennaExposureInfo",
    "alterationsDesc",
    "maintenanceProgramDesc"
})
public class TowerAntennaInfoType {

    @XmlElement(name = "YearBuilt")
    protected Date yearBuilt;
    @XmlElement(name = "ErectedDt")
    protected Date erectedDt;
    @XmlElement(name = "DesignTypeCd")
    protected DesignType designTypeCd;
    @XmlElement(name = "MaxWindSpeed")
    protected MEASUREMENT maxWindSpeed;
    @XmlElement(name = "DeIcingEquipmentInd")
    protected Boolean deIcingEquipmentInd;
    @XmlElement(name = "ElectricalProtectionCd")
    protected ElectricalProtection electricalProtectionCd;
    @XmlElement(name = "TowerOnBldgInd")
    protected Boolean towerOnBldgInd;
    @XmlElement(name = "TowerAntennaExposureInfo")
    protected List<TowerAntennaExposureInfoType> towerAntennaExposureInfo;
    @XmlElement(name = "AlterationsDesc")
    protected C255 alterationsDesc;
    @XmlElement(name = "MaintenanceProgramDesc")
    protected C255 maintenanceProgramDesc;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "TowerErectorRef")
    @XmlIDREF
    protected Object towerErectorRef;

    /**
     * Gets the value of the yearBuilt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getYearBuilt() {
        return yearBuilt;
    }

    /**
     * Sets the value of the yearBuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setYearBuilt(Date value) {
        this.yearBuilt = value;
    }

    /**
     * Gets the value of the erectedDt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getErectedDt() {
        return erectedDt;
    }

    /**
     * Sets the value of the erectedDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setErectedDt(Date value) {
        this.erectedDt = value;
    }

    /**
     * Gets the value of the designTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link DesignType }
     *     
     */
    public DesignType getDesignTypeCd() {
        return designTypeCd;
    }

    /**
     * Sets the value of the designTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesignType }
     *     
     */
    public void setDesignTypeCd(DesignType value) {
        this.designTypeCd = value;
    }

    /**
     * Gets the value of the maxWindSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link MEASUREMENT }
     *     
     */
    public MEASUREMENT getMaxWindSpeed() {
        return maxWindSpeed;
    }

    /**
     * Sets the value of the maxWindSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEASUREMENT }
     *     
     */
    public void setMaxWindSpeed(MEASUREMENT value) {
        this.maxWindSpeed = value;
    }

    /**
     * Gets the value of the deIcingEquipmentInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getDeIcingEquipmentInd() {
        return deIcingEquipmentInd;
    }

    /**
     * Sets the value of the deIcingEquipmentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeIcingEquipmentInd(Boolean value) {
        this.deIcingEquipmentInd = value;
    }

    /**
     * Gets the value of the electricalProtectionCd property.
     * 
     * @return
     *     possible object is
     *     {@link ElectricalProtection }
     *     
     */
    public ElectricalProtection getElectricalProtectionCd() {
        return electricalProtectionCd;
    }

    /**
     * Sets the value of the electricalProtectionCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectricalProtection }
     *     
     */
    public void setElectricalProtectionCd(ElectricalProtection value) {
        this.electricalProtectionCd = value;
    }

    /**
     * Gets the value of the towerOnBldgInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getTowerOnBldgInd() {
        return towerOnBldgInd;
    }

    /**
     * Sets the value of the towerOnBldgInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTowerOnBldgInd(Boolean value) {
        this.towerOnBldgInd = value;
    }

    /**
     * Gets the value of the towerAntennaExposureInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the towerAntennaExposureInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTowerAntennaExposureInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TowerAntennaExposureInfoType }
     * 
     * 
     */
    public List<TowerAntennaExposureInfoType> getTowerAntennaExposureInfo() {
        if (towerAntennaExposureInfo == null) {
            towerAntennaExposureInfo = new ArrayList<TowerAntennaExposureInfoType>();
        }
        return this.towerAntennaExposureInfo;
    }

    /**
     * Gets the value of the alterationsDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getAlterationsDesc() {
        return alterationsDesc;
    }

    /**
     * Sets the value of the alterationsDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setAlterationsDesc(C255 value) {
        this.alterationsDesc = value;
    }

    /**
     * Gets the value of the maintenanceProgramDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getMaintenanceProgramDesc() {
        return maintenanceProgramDesc;
    }

    /**
     * Sets the value of the maintenanceProgramDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setMaintenanceProgramDesc(C255 value) {
        this.maintenanceProgramDesc = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the towerErectorRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTowerErectorRef() {
        return towerErectorRef;
    }

    /**
     * Sets the value of the towerErectorRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTowerErectorRef(Object value) {
        this.towerErectorRef = value;
    }

}
