//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EditScope_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EditScope_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}RestrictedContextPath"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EditCase" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DefaultEditCase" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EditScope_Type", propOrder = {
    "restrictedContextPath",
    "editCase",
    "defaultEditCase"
})
public class EditScopeType {

    @XmlElement(name = "RestrictedContextPath", required = true)
    protected CInfinite restrictedContextPath;
    @XmlElement(name = "EditCase", required = true)
    protected List<EditCaseType> editCase;
    @XmlElement(name = "DefaultEditCase")
    protected DefaultEditCaseType defaultEditCase;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the restrictedContextPath property.
     * 
     * @return
     *     possible object is
     *     {@link CInfinite }
     *     
     */
    public CInfinite getRestrictedContextPath() {
        return restrictedContextPath;
    }

    /**
     * Sets the value of the restrictedContextPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link CInfinite }
     *     
     */
    public void setRestrictedContextPath(CInfinite value) {
        this.restrictedContextPath = value;
    }

    /**
     * Gets the value of the editCase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the editCase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEditCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EditCaseType }
     * 
     * 
     */
    public List<EditCaseType> getEditCase() {
        if (editCase == null) {
            editCase = new ArrayList<EditCaseType>();
        }
        return this.editCase;
    }

    /**
     * Gets the value of the defaultEditCase property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultEditCaseType }
     *     
     */
    public DefaultEditCaseType getDefaultEditCase() {
        return defaultEditCase;
    }

    /**
     * Sets the value of the defaultEditCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultEditCaseType }
     *     
     */
    public void setDefaultEditCase(DefaultEditCaseType value) {
        this.defaultEditCase = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
