//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErrorsAndOmissionsLineBusiness_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ErrorsAndOmissionsLineBusiness_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PCLINEBUSINESS">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CommlCoverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CommlSalesRevenueHistoryAndProjections" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CommlMajorRevenueSource" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SubcontractedWorkPct" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AverageProjectCostAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AverageProjectTerm" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LegalReviewTestingCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CommlParentOrSubsidiaryInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}QuestionAnswer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ErrorsAndOmissionsLineBusiness_Type", propOrder = {
    "commlCoverage",
    "commlSalesRevenueHistoryAndProjections",
    "commlMajorRevenueSource",
    "subcontractedWorkPct",
    "averageProjectCostAmt",
    "averageProjectTerm",
    "legalReviewTestingCd",
    "commlParentOrSubsidiaryInfo",
    "questionAnswer"
})
public class ErrorsAndOmissionsLineBusinessType
    extends PCLINEBUSINESS
{

    @XmlElement(name = "CommlCoverage")
    protected List<CommlCoverageType> commlCoverage;
    @XmlElement(name = "CommlSalesRevenueHistoryAndProjections")
    protected CommlSalesRevenueHistoryAndProjectionsType commlSalesRevenueHistoryAndProjections;
    @XmlElement(name = "CommlMajorRevenueSource")
    protected CommlMajorRevenueSourceType commlMajorRevenueSource;
    @XmlElement(name = "SubcontractedWorkPct")
    protected PercentLong subcontractedWorkPct;
    @XmlElement(name = "AverageProjectCostAmt")
    protected CURRENCY averageProjectCostAmt;
    @XmlElement(name = "AverageProjectTerm")
    protected MEASUREMENT averageProjectTerm;
    @XmlElement(name = "LegalReviewTestingCd")
    protected TestingType legalReviewTestingCd;
    @XmlElement(name = "CommlParentOrSubsidiaryInfo")
    protected List<CommlParentOrSubsidiaryInfoType> commlParentOrSubsidiaryInfo;
    @XmlElement(name = "QuestionAnswer")
    protected List<QuestionAnswerType> questionAnswer;

    /**
     * Gets the value of the commlCoverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commlCoverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommlCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommlCoverageType }
     * 
     * 
     */
    public List<CommlCoverageType> getCommlCoverage() {
        if (commlCoverage == null) {
            commlCoverage = new ArrayList<CommlCoverageType>();
        }
        return this.commlCoverage;
    }

    /**
     * Gets the value of the commlSalesRevenueHistoryAndProjections property.
     * 
     * @return
     *     possible object is
     *     {@link CommlSalesRevenueHistoryAndProjectionsType }
     *     
     */
    public CommlSalesRevenueHistoryAndProjectionsType getCommlSalesRevenueHistoryAndProjections() {
        return commlSalesRevenueHistoryAndProjections;
    }

    /**
     * Sets the value of the commlSalesRevenueHistoryAndProjections property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommlSalesRevenueHistoryAndProjectionsType }
     *     
     */
    public void setCommlSalesRevenueHistoryAndProjections(CommlSalesRevenueHistoryAndProjectionsType value) {
        this.commlSalesRevenueHistoryAndProjections = value;
    }

    /**
     * Gets the value of the commlMajorRevenueSource property.
     * 
     * @return
     *     possible object is
     *     {@link CommlMajorRevenueSourceType }
     *     
     */
    public CommlMajorRevenueSourceType getCommlMajorRevenueSource() {
        return commlMajorRevenueSource;
    }

    /**
     * Sets the value of the commlMajorRevenueSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommlMajorRevenueSourceType }
     *     
     */
    public void setCommlMajorRevenueSource(CommlMajorRevenueSourceType value) {
        this.commlMajorRevenueSource = value;
    }

    /**
     * Gets the value of the subcontractedWorkPct property.
     * 
     * @return
     *     possible object is
     *     {@link PercentLong }
     *     
     */
    public PercentLong getSubcontractedWorkPct() {
        return subcontractedWorkPct;
    }

    /**
     * Sets the value of the subcontractedWorkPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentLong }
     *     
     */
    public void setSubcontractedWorkPct(PercentLong value) {
        this.subcontractedWorkPct = value;
    }

    /**
     * Gets the value of the averageProjectCostAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getAverageProjectCostAmt() {
        return averageProjectCostAmt;
    }

    /**
     * Sets the value of the averageProjectCostAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setAverageProjectCostAmt(CURRENCY value) {
        this.averageProjectCostAmt = value;
    }

    /**
     * Gets the value of the averageProjectTerm property.
     * 
     * @return
     *     possible object is
     *     {@link MEASUREMENT }
     *     
     */
    public MEASUREMENT getAverageProjectTerm() {
        return averageProjectTerm;
    }

    /**
     * Sets the value of the averageProjectTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEASUREMENT }
     *     
     */
    public void setAverageProjectTerm(MEASUREMENT value) {
        this.averageProjectTerm = value;
    }

    /**
     * Gets the value of the legalReviewTestingCd property.
     * 
     * @return
     *     possible object is
     *     {@link TestingType }
     *     
     */
    public TestingType getLegalReviewTestingCd() {
        return legalReviewTestingCd;
    }

    /**
     * Sets the value of the legalReviewTestingCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestingType }
     *     
     */
    public void setLegalReviewTestingCd(TestingType value) {
        this.legalReviewTestingCd = value;
    }

    /**
     * Gets the value of the commlParentOrSubsidiaryInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commlParentOrSubsidiaryInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommlParentOrSubsidiaryInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommlParentOrSubsidiaryInfoType }
     * 
     * 
     */
    public List<CommlParentOrSubsidiaryInfoType> getCommlParentOrSubsidiaryInfo() {
        if (commlParentOrSubsidiaryInfo == null) {
            commlParentOrSubsidiaryInfo = new ArrayList<CommlParentOrSubsidiaryInfoType>();
        }
        return this.commlParentOrSubsidiaryInfo;
    }

    /**
     * Gets the value of the questionAnswer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questionAnswer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestionAnswer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuestionAnswerType }
     * 
     * 
     */
    public List<QuestionAnswerType> getQuestionAnswer() {
        if (questionAnswer == null) {
            questionAnswer = new ArrayList<QuestionAnswerType>();
        }
        return this.questionAnswer;
    }

}
