//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ExposureInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExposureInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ExposureCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}Description" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PropertyClassCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PropertySubClassCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PerformedForCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}InsuranceRequestedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}OffPremisesInd" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PremiumBasisCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}Exposure" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}TotalReceiptsPct" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DayCd" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ClienteleAgeCd" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}QuestionAnswer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *       &lt;attribute name="LocationRef" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IDREF" />
 *       &lt;attribute name="SubLocationRef" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExposureInfo_Type", propOrder = {
    "exposureCd",
    "description",
    "propertyClassCd",
    "propertySubClassCd",
    "performedForCd",
    "insuranceRequestedInd",
    "offPremisesInd",
    "premiumBasisCd",
    "exposure",
    "totalReceiptsPct",
    "dayCd",
    "clienteleAgeCd",
    "questionAnswer"
})
public class ExposureInfoType {

    @XmlElement(name = "ExposureCd")
    protected Exposures exposureCd;
    @XmlElement(name = "Description")
    protected C255 description;
    @XmlElement(name = "PropertyClassCd")
    protected Risk propertyClassCd;
    @XmlElement(name = "PropertySubClassCd")
    protected SubRisk propertySubClassCd;
    @XmlElement(name = "PerformedForCd")
    protected PerformedFor performedForCd;
    @XmlElement(name = "InsuranceRequestedInd")
    protected Boolean insuranceRequestedInd;
    @XmlElement(name = "OffPremisesInd")
    protected List<Boolean> offPremisesInd;
    @XmlElement(name = "PremiumBasisCd")
    protected PremiumBase premiumBasisCd;
    @XmlElement(name = "Exposure")
    protected Decimal exposure;
    @XmlElement(name = "TotalReceiptsPct")
    protected PercentDecimal totalReceiptsPct;
    @XmlElement(name = "DayCd")
    protected List<Days> dayCd;
    @XmlElement(name = "ClienteleAgeCd")
    protected List<ClienteleAge> clienteleAgeCd;
    @XmlElement(name = "QuestionAnswer")
    protected List<QuestionAnswerType> questionAnswer;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "LocationRef")
    @XmlIDREF
    protected Object locationRef;
    @XmlAttribute(name = "SubLocationRef")
    @XmlIDREF
    protected Object subLocationRef;

    /**
     * Gets the value of the exposureCd property.
     * 
     * @return
     *     possible object is
     *     {@link Exposures }
     *     
     */
    public Exposures getExposureCd() {
        return exposureCd;
    }

    /**
     * Sets the value of the exposureCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exposures }
     *     
     */
    public void setExposureCd(Exposures value) {
        this.exposureCd = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setDescription(C255 value) {
        this.description = value;
    }

    /**
     * Gets the value of the propertyClassCd property.
     * 
     * @return
     *     possible object is
     *     {@link Risk }
     *     
     */
    public Risk getPropertyClassCd() {
        return propertyClassCd;
    }

    /**
     * Sets the value of the propertyClassCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Risk }
     *     
     */
    public void setPropertyClassCd(Risk value) {
        this.propertyClassCd = value;
    }

    /**
     * Gets the value of the propertySubClassCd property.
     * 
     * @return
     *     possible object is
     *     {@link SubRisk }
     *     
     */
    public SubRisk getPropertySubClassCd() {
        return propertySubClassCd;
    }

    /**
     * Sets the value of the propertySubClassCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubRisk }
     *     
     */
    public void setPropertySubClassCd(SubRisk value) {
        this.propertySubClassCd = value;
    }

    /**
     * Gets the value of the performedForCd property.
     * 
     * @return
     *     possible object is
     *     {@link PerformedFor }
     *     
     */
    public PerformedFor getPerformedForCd() {
        return performedForCd;
    }

    /**
     * Sets the value of the performedForCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformedFor }
     *     
     */
    public void setPerformedForCd(PerformedFor value) {
        this.performedForCd = value;
    }

    /**
     * Gets the value of the insuranceRequestedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInsuranceRequestedInd() {
        return insuranceRequestedInd;
    }

    /**
     * Sets the value of the insuranceRequestedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsuranceRequestedInd(Boolean value) {
        this.insuranceRequestedInd = value;
    }

    /**
     * Gets the value of the offPremisesInd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offPremisesInd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffPremisesInd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getOffPremisesInd() {
        if (offPremisesInd == null) {
            offPremisesInd = new ArrayList<Boolean>();
        }
        return this.offPremisesInd;
    }

    /**
     * Gets the value of the premiumBasisCd property.
     * 
     * @return
     *     possible object is
     *     {@link PremiumBase }
     *     
     */
    public PremiumBase getPremiumBasisCd() {
        return premiumBasisCd;
    }

    /**
     * Sets the value of the premiumBasisCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PremiumBase }
     *     
     */
    public void setPremiumBasisCd(PremiumBase value) {
        this.premiumBasisCd = value;
    }

    /**
     * Gets the value of the exposure property.
     * 
     * @return
     *     possible object is
     *     {@link Decimal }
     *     
     */
    public Decimal getExposure() {
        return exposure;
    }

    /**
     * Sets the value of the exposure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decimal }
     *     
     */
    public void setExposure(Decimal value) {
        this.exposure = value;
    }

    /**
     * Gets the value of the totalReceiptsPct property.
     * 
     * @return
     *     possible object is
     *     {@link PercentDecimal }
     *     
     */
    public PercentDecimal getTotalReceiptsPct() {
        return totalReceiptsPct;
    }

    /**
     * Sets the value of the totalReceiptsPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentDecimal }
     *     
     */
    public void setTotalReceiptsPct(PercentDecimal value) {
        this.totalReceiptsPct = value;
    }

    /**
     * Gets the value of the dayCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dayCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDayCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Days }
     * 
     * 
     */
    public List<Days> getDayCd() {
        if (dayCd == null) {
            dayCd = new ArrayList<Days>();
        }
        return this.dayCd;
    }

    /**
     * Gets the value of the clienteleAgeCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clienteleAgeCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClienteleAgeCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClienteleAge }
     * 
     * 
     */
    public List<ClienteleAge> getClienteleAgeCd() {
        if (clienteleAgeCd == null) {
            clienteleAgeCd = new ArrayList<ClienteleAge>();
        }
        return this.clienteleAgeCd;
    }

    /**
     * Gets the value of the questionAnswer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questionAnswer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestionAnswer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuestionAnswerType }
     * 
     * 
     */
    public List<QuestionAnswerType> getQuestionAnswer() {
        if (questionAnswer == null) {
            questionAnswer = new ArrayList<QuestionAnswerType>();
        }
        return this.questionAnswer;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the locationRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLocationRef() {
        return locationRef;
    }

    /**
     * Sets the value of the locationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLocationRef(Object value) {
        this.locationRef = value;
    }

    /**
     * Gets the value of the subLocationRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSubLocationRef() {
        return subLocationRef;
    }

    /**
     * Sets the value of the subLocationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSubLocationRef(Object value) {
        this.subLocationRef = value;
    }

}
