//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FiduciaryBond_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FiduciaryBond_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AuditFrequencyCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AllowancePerMonthAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AnyDisputesInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AppointmentDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}BlockedAccountsInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CaseCauseNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CaseTitle" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ContinuingBusinessForEstateInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CourtApprovedAllowanceForWardInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DeathDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IndebtedToEstateInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IsTheAppointmentOrWillBeingContestedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}JointControlAssetsInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NatureEstate" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}OtherSafeguardsDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EstateInterestPct" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ProbateSummaryDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SolePrincipalEstateBeneficiaryInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SucceedingAnotherFiduciaryInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EstatesLiquidAssetsAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}Beneficiaries" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}MiscParty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}TotalEstateAssetsAmt" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FiduciaryBond_Type", propOrder = {
    "auditFrequencyCd",
    "allowancePerMonthAmt",
    "anyDisputesInd",
    "appointmentDt",
    "blockedAccountsInd",
    "caseCauseNumber",
    "caseTitle",
    "continuingBusinessForEstateInd",
    "courtApprovedAllowanceForWardInd",
    "deathDt",
    "indebtedToEstateInd",
    "isTheAppointmentOrWillBeingContestedInd",
    "jointControlAssetsInd",
    "natureEstate",
    "otherSafeguardsDesc",
    "estateInterestPct",
    "probateSummaryDesc",
    "solePrincipalEstateBeneficiaryInd",
    "succeedingAnotherFiduciaryInd",
    "estatesLiquidAssetsAmt",
    "beneficiaries",
    "miscParty",
    "totalEstateAssetsAmt"
})
public class FiduciaryBondType {

    @XmlElement(name = "AuditFrequencyCd")
    protected Frequency auditFrequencyCd;
    @XmlElement(name = "AllowancePerMonthAmt")
    protected CURRENCY allowancePerMonthAmt;
    @XmlElement(name = "AnyDisputesInd")
    protected Boolean anyDisputesInd;
    @XmlElement(name = "AppointmentDt")
    protected Date appointmentDt;
    @XmlElement(name = "BlockedAccountsInd")
    protected Boolean blockedAccountsInd;
    @XmlElement(name = "CaseCauseNumber")
    protected C30 caseCauseNumber;
    @XmlElement(name = "CaseTitle")
    protected C100 caseTitle;
    @XmlElement(name = "ContinuingBusinessForEstateInd")
    protected Boolean continuingBusinessForEstateInd;
    @XmlElement(name = "CourtApprovedAllowanceForWardInd")
    protected Boolean courtApprovedAllowanceForWardInd;
    @XmlElement(name = "DeathDt")
    protected Date deathDt;
    @XmlElement(name = "IndebtedToEstateInd")
    protected Boolean indebtedToEstateInd;
    @XmlElement(name = "IsTheAppointmentOrWillBeingContestedInd")
    protected Boolean isTheAppointmentOrWillBeingContestedInd;
    @XmlElement(name = "JointControlAssetsInd")
    protected Boolean jointControlAssetsInd;
    @XmlElement(name = "NatureEstate")
    protected C20 natureEstate;
    @XmlElement(name = "OtherSafeguardsDesc")
    protected C255 otherSafeguardsDesc;
    @XmlElement(name = "EstateInterestPct")
    protected PercentLong estateInterestPct;
    @XmlElement(name = "ProbateSummaryDesc")
    protected C255 probateSummaryDesc;
    @XmlElement(name = "SolePrincipalEstateBeneficiaryInd")
    protected Boolean solePrincipalEstateBeneficiaryInd;
    @XmlElement(name = "SucceedingAnotherFiduciaryInd")
    protected Boolean succeedingAnotherFiduciaryInd;
    @XmlElement(name = "EstatesLiquidAssetsAmt")
    protected CURRENCY estatesLiquidAssetsAmt;
    @XmlElement(name = "Beneficiaries")
    protected List<BeneficiariesType> beneficiaries;
    @XmlElement(name = "MiscParty")
    protected List<MiscPartyType> miscParty;
    @XmlElement(name = "TotalEstateAssetsAmt")
    protected CURRENCY totalEstateAssetsAmt;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the auditFrequencyCd property.
     * 
     * @return
     *     possible object is
     *     {@link Frequency }
     *     
     */
    public Frequency getAuditFrequencyCd() {
        return auditFrequencyCd;
    }

    /**
     * Sets the value of the auditFrequencyCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frequency }
     *     
     */
    public void setAuditFrequencyCd(Frequency value) {
        this.auditFrequencyCd = value;
    }

    /**
     * Gets the value of the allowancePerMonthAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getAllowancePerMonthAmt() {
        return allowancePerMonthAmt;
    }

    /**
     * Sets the value of the allowancePerMonthAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setAllowancePerMonthAmt(CURRENCY value) {
        this.allowancePerMonthAmt = value;
    }

    /**
     * Gets the value of the anyDisputesInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAnyDisputesInd() {
        return anyDisputesInd;
    }

    /**
     * Sets the value of the anyDisputesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnyDisputesInd(Boolean value) {
        this.anyDisputesInd = value;
    }

    /**
     * Gets the value of the appointmentDt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getAppointmentDt() {
        return appointmentDt;
    }

    /**
     * Sets the value of the appointmentDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setAppointmentDt(Date value) {
        this.appointmentDt = value;
    }

    /**
     * Gets the value of the blockedAccountsInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getBlockedAccountsInd() {
        return blockedAccountsInd;
    }

    /**
     * Sets the value of the blockedAccountsInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlockedAccountsInd(Boolean value) {
        this.blockedAccountsInd = value;
    }

    /**
     * Gets the value of the caseCauseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link C30 }
     *     
     */
    public C30 getCaseCauseNumber() {
        return caseCauseNumber;
    }

    /**
     * Sets the value of the caseCauseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link C30 }
     *     
     */
    public void setCaseCauseNumber(C30 value) {
        this.caseCauseNumber = value;
    }

    /**
     * Gets the value of the caseTitle property.
     * 
     * @return
     *     possible object is
     *     {@link C100 }
     *     
     */
    public C100 getCaseTitle() {
        return caseTitle;
    }

    /**
     * Sets the value of the caseTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link C100 }
     *     
     */
    public void setCaseTitle(C100 value) {
        this.caseTitle = value;
    }

    /**
     * Gets the value of the continuingBusinessForEstateInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getContinuingBusinessForEstateInd() {
        return continuingBusinessForEstateInd;
    }

    /**
     * Sets the value of the continuingBusinessForEstateInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContinuingBusinessForEstateInd(Boolean value) {
        this.continuingBusinessForEstateInd = value;
    }

    /**
     * Gets the value of the courtApprovedAllowanceForWardInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCourtApprovedAllowanceForWardInd() {
        return courtApprovedAllowanceForWardInd;
    }

    /**
     * Sets the value of the courtApprovedAllowanceForWardInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCourtApprovedAllowanceForWardInd(Boolean value) {
        this.courtApprovedAllowanceForWardInd = value;
    }

    /**
     * Gets the value of the deathDt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDeathDt() {
        return deathDt;
    }

    /**
     * Sets the value of the deathDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDeathDt(Date value) {
        this.deathDt = value;
    }

    /**
     * Gets the value of the indebtedToEstateInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIndebtedToEstateInd() {
        return indebtedToEstateInd;
    }

    /**
     * Sets the value of the indebtedToEstateInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndebtedToEstateInd(Boolean value) {
        this.indebtedToEstateInd = value;
    }

    /**
     * Gets the value of the isTheAppointmentOrWillBeingContestedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getIsTheAppointmentOrWillBeingContestedInd() {
        return isTheAppointmentOrWillBeingContestedInd;
    }

    /**
     * Sets the value of the isTheAppointmentOrWillBeingContestedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTheAppointmentOrWillBeingContestedInd(Boolean value) {
        this.isTheAppointmentOrWillBeingContestedInd = value;
    }

    /**
     * Gets the value of the jointControlAssetsInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getJointControlAssetsInd() {
        return jointControlAssetsInd;
    }

    /**
     * Sets the value of the jointControlAssetsInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJointControlAssetsInd(Boolean value) {
        this.jointControlAssetsInd = value;
    }

    /**
     * Gets the value of the natureEstate property.
     * 
     * @return
     *     possible object is
     *     {@link C20 }
     *     
     */
    public C20 getNatureEstate() {
        return natureEstate;
    }

    /**
     * Sets the value of the natureEstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link C20 }
     *     
     */
    public void setNatureEstate(C20 value) {
        this.natureEstate = value;
    }

    /**
     * Gets the value of the otherSafeguardsDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getOtherSafeguardsDesc() {
        return otherSafeguardsDesc;
    }

    /**
     * Sets the value of the otherSafeguardsDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setOtherSafeguardsDesc(C255 value) {
        this.otherSafeguardsDesc = value;
    }

    /**
     * Gets the value of the estateInterestPct property.
     * 
     * @return
     *     possible object is
     *     {@link PercentLong }
     *     
     */
    public PercentLong getEstateInterestPct() {
        return estateInterestPct;
    }

    /**
     * Sets the value of the estateInterestPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentLong }
     *     
     */
    public void setEstateInterestPct(PercentLong value) {
        this.estateInterestPct = value;
    }

    /**
     * Gets the value of the probateSummaryDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getProbateSummaryDesc() {
        return probateSummaryDesc;
    }

    /**
     * Sets the value of the probateSummaryDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setProbateSummaryDesc(C255 value) {
        this.probateSummaryDesc = value;
    }

    /**
     * Gets the value of the solePrincipalEstateBeneficiaryInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSolePrincipalEstateBeneficiaryInd() {
        return solePrincipalEstateBeneficiaryInd;
    }

    /**
     * Sets the value of the solePrincipalEstateBeneficiaryInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSolePrincipalEstateBeneficiaryInd(Boolean value) {
        this.solePrincipalEstateBeneficiaryInd = value;
    }

    /**
     * Gets the value of the succeedingAnotherFiduciaryInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSucceedingAnotherFiduciaryInd() {
        return succeedingAnotherFiduciaryInd;
    }

    /**
     * Sets the value of the succeedingAnotherFiduciaryInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSucceedingAnotherFiduciaryInd(Boolean value) {
        this.succeedingAnotherFiduciaryInd = value;
    }

    /**
     * Gets the value of the estatesLiquidAssetsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getEstatesLiquidAssetsAmt() {
        return estatesLiquidAssetsAmt;
    }

    /**
     * Sets the value of the estatesLiquidAssetsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setEstatesLiquidAssetsAmt(CURRENCY value) {
        this.estatesLiquidAssetsAmt = value;
    }

    /**
     * Gets the value of the beneficiaries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beneficiaries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeneficiaries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BeneficiariesType }
     * 
     * 
     */
    public List<BeneficiariesType> getBeneficiaries() {
        if (beneficiaries == null) {
            beneficiaries = new ArrayList<BeneficiariesType>();
        }
        return this.beneficiaries;
    }

    /**
     * Gets the value of the miscParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miscParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiscParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MiscPartyType }
     * 
     * 
     */
    public List<MiscPartyType> getMiscParty() {
        if (miscParty == null) {
            miscParty = new ArrayList<MiscPartyType>();
        }
        return this.miscParty;
    }

    /**
     * Gets the value of the totalEstateAssetsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getTotalEstateAssetsAmt() {
        return totalEstateAssetsAmt;
    }

    /**
     * Sets the value of the totalEstateAssetsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setTotalEstateAssetsAmt(CURRENCY value) {
        this.totalEstateAssetsAmt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
