//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Fueling_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fueling_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SelfServInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}InsuredFuelsInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FuelTruckInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}GasPumpInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FuelingOnPremInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AVGasSalesInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}JetFuelSalesInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AutoFuelSalesInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FuelingDoneDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumGallonsAirline" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumGallonsGenAviation" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumGallonsMilitary" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumGallonsUnderground" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumGallonsAboveGround" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *       &lt;attribute name="LocationRef" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IDREF" />
 *       &lt;attribute name="SubLocationRef" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fueling_Type", propOrder = {
    "selfServInd",
    "insuredFuelsInd",
    "fuelTruckInd",
    "gasPumpInd",
    "fuelingOnPremInd",
    "avGasSalesInd",
    "jetFuelSalesInd",
    "autoFuelSalesInd",
    "fuelingDoneDesc",
    "numGallonsAirline",
    "numGallonsGenAviation",
    "numGallonsMilitary",
    "numGallonsUnderground",
    "numGallonsAboveGround"
})
public class FuelingType {

    @XmlElement(name = "SelfServInd")
    protected Boolean selfServInd;
    @XmlElement(name = "InsuredFuelsInd")
    protected Boolean insuredFuelsInd;
    @XmlElement(name = "FuelTruckInd")
    protected Boolean fuelTruckInd;
    @XmlElement(name = "GasPumpInd")
    protected Boolean gasPumpInd;
    @XmlElement(name = "FuelingOnPremInd")
    protected Boolean fuelingOnPremInd;
    @XmlElement(name = "AVGasSalesInd")
    protected Boolean avGasSalesInd;
    @XmlElement(name = "JetFuelSalesInd")
    protected Boolean jetFuelSalesInd;
    @XmlElement(name = "AutoFuelSalesInd")
    protected Boolean autoFuelSalesInd;
    @XmlElement(name = "FuelingDoneDesc")
    protected C255 fuelingDoneDesc;
    @XmlElement(name = "NumGallonsAirline")
    protected Long numGallonsAirline;
    @XmlElement(name = "NumGallonsGenAviation")
    protected Long numGallonsGenAviation;
    @XmlElement(name = "NumGallonsMilitary")
    protected Long numGallonsMilitary;
    @XmlElement(name = "NumGallonsUnderground")
    protected Long numGallonsUnderground;
    @XmlElement(name = "NumGallonsAboveGround")
    protected Long numGallonsAboveGround;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "LocationRef")
    @XmlIDREF
    protected Object locationRef;
    @XmlAttribute(name = "SubLocationRef")
    @XmlIDREF
    protected Object subLocationRef;

    /**
     * Gets the value of the selfServInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSelfServInd() {
        return selfServInd;
    }

    /**
     * Sets the value of the selfServInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelfServInd(Boolean value) {
        this.selfServInd = value;
    }

    /**
     * Gets the value of the insuredFuelsInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInsuredFuelsInd() {
        return insuredFuelsInd;
    }

    /**
     * Sets the value of the insuredFuelsInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInsuredFuelsInd(Boolean value) {
        this.insuredFuelsInd = value;
    }

    /**
     * Gets the value of the fuelTruckInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFuelTruckInd() {
        return fuelTruckInd;
    }

    /**
     * Sets the value of the fuelTruckInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFuelTruckInd(Boolean value) {
        this.fuelTruckInd = value;
    }

    /**
     * Gets the value of the gasPumpInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getGasPumpInd() {
        return gasPumpInd;
    }

    /**
     * Sets the value of the gasPumpInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGasPumpInd(Boolean value) {
        this.gasPumpInd = value;
    }

    /**
     * Gets the value of the fuelingOnPremInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFuelingOnPremInd() {
        return fuelingOnPremInd;
    }

    /**
     * Sets the value of the fuelingOnPremInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFuelingOnPremInd(Boolean value) {
        this.fuelingOnPremInd = value;
    }

    /**
     * Gets the value of the avGasSalesInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAVGasSalesInd() {
        return avGasSalesInd;
    }

    /**
     * Sets the value of the avGasSalesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAVGasSalesInd(Boolean value) {
        this.avGasSalesInd = value;
    }

    /**
     * Gets the value of the jetFuelSalesInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getJetFuelSalesInd() {
        return jetFuelSalesInd;
    }

    /**
     * Sets the value of the jetFuelSalesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJetFuelSalesInd(Boolean value) {
        this.jetFuelSalesInd = value;
    }

    /**
     * Gets the value of the autoFuelSalesInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutoFuelSalesInd() {
        return autoFuelSalesInd;
    }

    /**
     * Sets the value of the autoFuelSalesInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoFuelSalesInd(Boolean value) {
        this.autoFuelSalesInd = value;
    }

    /**
     * Gets the value of the fuelingDoneDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getFuelingDoneDesc() {
        return fuelingDoneDesc;
    }

    /**
     * Sets the value of the fuelingDoneDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setFuelingDoneDesc(C255 value) {
        this.fuelingDoneDesc = value;
    }

    /**
     * Gets the value of the numGallonsAirline property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumGallonsAirline() {
        return numGallonsAirline;
    }

    /**
     * Sets the value of the numGallonsAirline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumGallonsAirline(Long value) {
        this.numGallonsAirline = value;
    }

    /**
     * Gets the value of the numGallonsGenAviation property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumGallonsGenAviation() {
        return numGallonsGenAviation;
    }

    /**
     * Sets the value of the numGallonsGenAviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumGallonsGenAviation(Long value) {
        this.numGallonsGenAviation = value;
    }

    /**
     * Gets the value of the numGallonsMilitary property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumGallonsMilitary() {
        return numGallonsMilitary;
    }

    /**
     * Sets the value of the numGallonsMilitary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumGallonsMilitary(Long value) {
        this.numGallonsMilitary = value;
    }

    /**
     * Gets the value of the numGallonsUnderground property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumGallonsUnderground() {
        return numGallonsUnderground;
    }

    /**
     * Sets the value of the numGallonsUnderground property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumGallonsUnderground(Long value) {
        this.numGallonsUnderground = value;
    }

    /**
     * Gets the value of the numGallonsAboveGround property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNumGallonsAboveGround() {
        return numGallonsAboveGround;
    }

    /**
     * Sets the value of the numGallonsAboveGround property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNumGallonsAboveGround(Long value) {
        this.numGallonsAboveGround = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the locationRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLocationRef() {
        return locationRef;
    }

    /**
     * Sets the value of the locationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLocationRef(Object value) {
        this.locationRef = value;
    }

    /**
     * Gets the value of the subLocationRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSubLocationRef() {
        return subLocationRef;
    }

    /**
     * Sets the value of the subLocationRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSubLocationRef(Object value) {
        this.subLocationRef = value;
    }

}
