//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MiscellaneousBond_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MiscellaneousBond_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LossDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EndorsedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}InstrumentJudgementObtainedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}InstrumentSubjectToLitigationInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LeasedPropertyDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LeaseTerm" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LossNoticeMadeInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LostInstrumentDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LostInstrumentNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LostInstrumentTypeDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SecuritiesMarketValueAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SecuritiesParValueAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PaymentStoppedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}RegisteredOwnerInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ValuationDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}MiscParty" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}BearerBondInd" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MiscellaneousBond_Type", propOrder = {
    "lossDesc",
    "endorsedInd",
    "instrumentJudgementObtainedInd",
    "instrumentSubjectToLitigationInd",
    "leasedPropertyDesc",
    "leaseTerm",
    "lossNoticeMadeInd",
    "lostInstrumentDt",
    "lostInstrumentNumber",
    "lostInstrumentTypeDesc",
    "securitiesMarketValueAmt",
    "securitiesParValueAmt",
    "paymentStoppedInd",
    "registeredOwnerInd",
    "valuationDt",
    "miscParty",
    "bearerBondInd"
})
public class MiscellaneousBondType {

    @XmlElement(name = "LossDesc")
    protected C255 lossDesc;
    @XmlElement(name = "EndorsedInd")
    protected Boolean endorsedInd;
    @XmlElement(name = "InstrumentJudgementObtainedInd")
    protected Boolean instrumentJudgementObtainedInd;
    @XmlElement(name = "InstrumentSubjectToLitigationInd")
    protected Boolean instrumentSubjectToLitigationInd;
    @XmlElement(name = "LeasedPropertyDesc")
    protected C255 leasedPropertyDesc;
    @XmlElement(name = "LeaseTerm")
    protected DURATION leaseTerm;
    @XmlElement(name = "LossNoticeMadeInd")
    protected Boolean lossNoticeMadeInd;
    @XmlElement(name = "LostInstrumentDt")
    protected Date lostInstrumentDt;
    @XmlElement(name = "LostInstrumentNumber")
    protected C20 lostInstrumentNumber;
    @XmlElement(name = "LostInstrumentTypeDesc")
    protected C255 lostInstrumentTypeDesc;
    @XmlElement(name = "SecuritiesMarketValueAmt")
    protected CURRENCY securitiesMarketValueAmt;
    @XmlElement(name = "SecuritiesParValueAmt")
    protected CURRENCY securitiesParValueAmt;
    @XmlElement(name = "PaymentStoppedInd")
    protected Boolean paymentStoppedInd;
    @XmlElement(name = "RegisteredOwnerInd")
    protected Boolean registeredOwnerInd;
    @XmlElement(name = "ValuationDt")
    protected Date valuationDt;
    @XmlElement(name = "MiscParty")
    protected List<MiscPartyType> miscParty;
    @XmlElement(name = "BearerBondInd")
    protected Boolean bearerBondInd;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the lossDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getLossDesc() {
        return lossDesc;
    }

    /**
     * Sets the value of the lossDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setLossDesc(C255 value) {
        this.lossDesc = value;
    }

    /**
     * Gets the value of the endorsedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getEndorsedInd() {
        return endorsedInd;
    }

    /**
     * Sets the value of the endorsedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEndorsedInd(Boolean value) {
        this.endorsedInd = value;
    }

    /**
     * Gets the value of the instrumentJudgementObtainedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInstrumentJudgementObtainedInd() {
        return instrumentJudgementObtainedInd;
    }

    /**
     * Sets the value of the instrumentJudgementObtainedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInstrumentJudgementObtainedInd(Boolean value) {
        this.instrumentJudgementObtainedInd = value;
    }

    /**
     * Gets the value of the instrumentSubjectToLitigationInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInstrumentSubjectToLitigationInd() {
        return instrumentSubjectToLitigationInd;
    }

    /**
     * Sets the value of the instrumentSubjectToLitigationInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInstrumentSubjectToLitigationInd(Boolean value) {
        this.instrumentSubjectToLitigationInd = value;
    }

    /**
     * Gets the value of the leasedPropertyDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getLeasedPropertyDesc() {
        return leasedPropertyDesc;
    }

    /**
     * Sets the value of the leasedPropertyDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setLeasedPropertyDesc(C255 value) {
        this.leasedPropertyDesc = value;
    }

    /**
     * Gets the value of the leaseTerm property.
     * 
     * @return
     *     possible object is
     *     {@link DURATION }
     *     
     */
    public DURATION getLeaseTerm() {
        return leaseTerm;
    }

    /**
     * Sets the value of the leaseTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DURATION }
     *     
     */
    public void setLeaseTerm(DURATION value) {
        this.leaseTerm = value;
    }

    /**
     * Gets the value of the lossNoticeMadeInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getLossNoticeMadeInd() {
        return lossNoticeMadeInd;
    }

    /**
     * Sets the value of the lossNoticeMadeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLossNoticeMadeInd(Boolean value) {
        this.lossNoticeMadeInd = value;
    }

    /**
     * Gets the value of the lostInstrumentDt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getLostInstrumentDt() {
        return lostInstrumentDt;
    }

    /**
     * Sets the value of the lostInstrumentDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setLostInstrumentDt(Date value) {
        this.lostInstrumentDt = value;
    }

    /**
     * Gets the value of the lostInstrumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link C20 }
     *     
     */
    public C20 getLostInstrumentNumber() {
        return lostInstrumentNumber;
    }

    /**
     * Sets the value of the lostInstrumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link C20 }
     *     
     */
    public void setLostInstrumentNumber(C20 value) {
        this.lostInstrumentNumber = value;
    }

    /**
     * Gets the value of the lostInstrumentTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C255 }
     *     
     */
    public C255 getLostInstrumentTypeDesc() {
        return lostInstrumentTypeDesc;
    }

    /**
     * Sets the value of the lostInstrumentTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C255 }
     *     
     */
    public void setLostInstrumentTypeDesc(C255 value) {
        this.lostInstrumentTypeDesc = value;
    }

    /**
     * Gets the value of the securitiesMarketValueAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getSecuritiesMarketValueAmt() {
        return securitiesMarketValueAmt;
    }

    /**
     * Sets the value of the securitiesMarketValueAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setSecuritiesMarketValueAmt(CURRENCY value) {
        this.securitiesMarketValueAmt = value;
    }

    /**
     * Gets the value of the securitiesParValueAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getSecuritiesParValueAmt() {
        return securitiesParValueAmt;
    }

    /**
     * Sets the value of the securitiesParValueAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setSecuritiesParValueAmt(CURRENCY value) {
        this.securitiesParValueAmt = value;
    }

    /**
     * Gets the value of the paymentStoppedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getPaymentStoppedInd() {
        return paymentStoppedInd;
    }

    /**
     * Sets the value of the paymentStoppedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPaymentStoppedInd(Boolean value) {
        this.paymentStoppedInd = value;
    }

    /**
     * Gets the value of the registeredOwnerInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getRegisteredOwnerInd() {
        return registeredOwnerInd;
    }

    /**
     * Sets the value of the registeredOwnerInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegisteredOwnerInd(Boolean value) {
        this.registeredOwnerInd = value;
    }

    /**
     * Gets the value of the valuationDt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getValuationDt() {
        return valuationDt;
    }

    /**
     * Sets the value of the valuationDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setValuationDt(Date value) {
        this.valuationDt = value;
    }

    /**
     * Gets the value of the miscParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the miscParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMiscParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MiscPartyType }
     * 
     * 
     */
    public List<MiscPartyType> getMiscParty() {
        if (miscParty == null) {
            miscParty = new ArrayList<MiscPartyType>();
        }
        return this.miscParty;
    }

    /**
     * Gets the value of the bearerBondInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getBearerBondInd() {
        return bearerBondInd;
    }

    /**
     * Sets the value of the bearerBondInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBearerBondInd(Boolean value) {
        this.bearerBondInd = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
