//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for MonthlyLeaseholdInterestInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MonthlyLeaseholdInterestInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}BonusAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ImprovementsAndBettermentsAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PrepaidRentAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PaymentDt" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonthlyLeaseholdInterestInfo_Type", propOrder = {
    "bonusAmt",
    "improvementsAndBettermentsAmt",
    "prepaidRentAmt",
    "paymentDt"
})
public class MonthlyLeaseholdInterestInfoType {

    @XmlElement(name = "BonusAmt")
    protected CURRENCY bonusAmt;
    @XmlElement(name = "ImprovementsAndBettermentsAmt")
    protected CURRENCY improvementsAndBettermentsAmt;
    @XmlElement(name = "PrepaidRentAmt")
    protected CURRENCY prepaidRentAmt;
    @XmlElement(name = "PaymentDt")
    protected Date paymentDt;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the bonusAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getBonusAmt() {
        return bonusAmt;
    }

    /**
     * Sets the value of the bonusAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setBonusAmt(CURRENCY value) {
        this.bonusAmt = value;
    }

    /**
     * Gets the value of the improvementsAndBettermentsAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getImprovementsAndBettermentsAmt() {
        return improvementsAndBettermentsAmt;
    }

    /**
     * Sets the value of the improvementsAndBettermentsAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setImprovementsAndBettermentsAmt(CURRENCY value) {
        this.improvementsAndBettermentsAmt = value;
    }

    /**
     * Gets the value of the prepaidRentAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getPrepaidRentAmt() {
        return prepaidRentAmt;
    }

    /**
     * Sets the value of the prepaidRentAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setPrepaidRentAmt(CURRENCY value) {
        this.prepaidRentAmt = value;
    }

    /**
     * Gets the value of the paymentDt property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getPaymentDt() {
        return paymentDt;
    }

    /**
     * Sets the value of the paymentDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setPaymentDt(Date value) {
        this.paymentDt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
