//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PropertyScheduleModifications_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyScheduleModifications_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}BlanketNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}BlanketInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ExhibitedInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}InVaultInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ProfessionalCommercialUseInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CustomUseInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}QualifierTypeCd" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}NumUnits" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}Measure" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}AvgValuePerUnit" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ReportingPeriodCd" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyScheduleModifications_Type", propOrder = {
    "blanketNumber",
    "blanketInd",
    "exhibitedInd",
    "inVaultInd",
    "professionalCommercialUseInd",
    "customUseInd",
    "qualifierTypeCd",
    "numUnits",
    "measure",
    "avgValuePerUnit",
    "reportingPeriodCd"
})
public class PropertyScheduleModificationsType {

    @XmlElement(name = "BlanketNumber")
    protected Long blanketNumber;
    @XmlElement(name = "BlanketInd")
    protected Boolean blanketInd;
    @XmlElement(name = "ExhibitedInd")
    protected Boolean exhibitedInd;
    @XmlElement(name = "InVaultInd")
    protected Boolean inVaultInd;
    @XmlElement(name = "ProfessionalCommercialUseInd")
    protected Boolean professionalCommercialUseInd;
    @XmlElement(name = "CustomUseInd")
    protected Boolean customUseInd;
    @XmlElement(name = "QualifierTypeCd")
    protected List<RiskQualifier> qualifierTypeCd;
    @XmlElement(name = "NumUnits")
    protected Decimal numUnits;
    @XmlElement(name = "Measure")
    protected MEASUREMENT measure;
    @XmlElement(name = "AvgValuePerUnit")
    protected CURRENCY avgValuePerUnit;
    @XmlElement(name = "ReportingPeriodCd")
    protected Frequency reportingPeriodCd;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the blanketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBlanketNumber() {
        return blanketNumber;
    }

    /**
     * Sets the value of the blanketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBlanketNumber(Long value) {
        this.blanketNumber = value;
    }

    /**
     * Gets the value of the blanketInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getBlanketInd() {
        return blanketInd;
    }

    /**
     * Sets the value of the blanketInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlanketInd(Boolean value) {
        this.blanketInd = value;
    }

    /**
     * Gets the value of the exhibitedInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getExhibitedInd() {
        return exhibitedInd;
    }

    /**
     * Sets the value of the exhibitedInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExhibitedInd(Boolean value) {
        this.exhibitedInd = value;
    }

    /**
     * Gets the value of the inVaultInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getInVaultInd() {
        return inVaultInd;
    }

    /**
     * Sets the value of the inVaultInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInVaultInd(Boolean value) {
        this.inVaultInd = value;
    }

    /**
     * Gets the value of the professionalCommercialUseInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getProfessionalCommercialUseInd() {
        return professionalCommercialUseInd;
    }

    /**
     * Sets the value of the professionalCommercialUseInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProfessionalCommercialUseInd(Boolean value) {
        this.professionalCommercialUseInd = value;
    }

    /**
     * Gets the value of the customUseInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCustomUseInd() {
        return customUseInd;
    }

    /**
     * Sets the value of the customUseInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomUseInd(Boolean value) {
        this.customUseInd = value;
    }

    /**
     * Gets the value of the qualifierTypeCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifierTypeCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifierTypeCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RiskQualifier }
     * 
     * 
     */
    public List<RiskQualifier> getQualifierTypeCd() {
        if (qualifierTypeCd == null) {
            qualifierTypeCd = new ArrayList<RiskQualifier>();
        }
        return this.qualifierTypeCd;
    }

    /**
     * Gets the value of the numUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Decimal }
     *     
     */
    public Decimal getNumUnits() {
        return numUnits;
    }

    /**
     * Sets the value of the numUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decimal }
     *     
     */
    public void setNumUnits(Decimal value) {
        this.numUnits = value;
    }

    /**
     * Gets the value of the measure property.
     * 
     * @return
     *     possible object is
     *     {@link MEASUREMENT }
     *     
     */
    public MEASUREMENT getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEASUREMENT }
     *     
     */
    public void setMeasure(MEASUREMENT value) {
        this.measure = value;
    }

    /**
     * Gets the value of the avgValuePerUnit property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getAvgValuePerUnit() {
        return avgValuePerUnit;
    }

    /**
     * Sets the value of the avgValuePerUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setAvgValuePerUnit(CURRENCY value) {
        this.avgValuePerUnit = value;
    }

    /**
     * Gets the value of the reportingPeriodCd property.
     * 
     * @return
     *     possible object is
     *     {@link Frequency }
     *     
     */
    public Frequency getReportingPeriodCd() {
        return reportingPeriodCd;
    }

    /**
     * Sets the value of the reportingPeriodCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frequency }
     *     
     */
    public void setReportingPeriodCd(Frequency value) {
        this.reportingPeriodCd = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
