//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SafeVaultDoorChest_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SafeVaultDoorChest_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CombinationLockInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DoorChestTypeCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DoorRatingCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}DoorTypeCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}RelockingDeviceInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}TimeLockInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ItemDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SafeVaultDoorChest_Type", propOrder = {
    "combinationLockInd",
    "doorChestTypeCd",
    "doorRatingCd",
    "doorTypeCd",
    "relockingDeviceInd",
    "timeLockInd",
    "itemDefinition"
})
public class SafeVaultDoorChestType {

    @XmlElement(name = "CombinationLockInd")
    protected Boolean combinationLockInd;
    @XmlElement(name = "DoorChestTypeCd")
    protected DoorChestType doorChestTypeCd;
    @XmlElement(name = "DoorRatingCd")
    protected OpenEnum doorRatingCd;
    @XmlElement(name = "DoorTypeCd")
    protected SafeDoorType doorTypeCd;
    @XmlElement(name = "RelockingDeviceInd")
    protected Boolean relockingDeviceInd;
    @XmlElement(name = "TimeLockInd")
    protected Boolean timeLockInd;
    @XmlElement(name = "ItemDefinition")
    protected List<ItemDefinitionType2> itemDefinition;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the combinationLockInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getCombinationLockInd() {
        return combinationLockInd;
    }

    /**
     * Sets the value of the combinationLockInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCombinationLockInd(Boolean value) {
        this.combinationLockInd = value;
    }

    /**
     * Gets the value of the doorChestTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link DoorChestType }
     *     
     */
    public DoorChestType getDoorChestTypeCd() {
        return doorChestTypeCd;
    }

    /**
     * Sets the value of the doorChestTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoorChestType }
     *     
     */
    public void setDoorChestTypeCd(DoorChestType value) {
        this.doorChestTypeCd = value;
    }

    /**
     * Gets the value of the doorRatingCd property.
     * 
     * @return
     *     possible object is
     *     {@link OpenEnum }
     *     
     */
    public OpenEnum getDoorRatingCd() {
        return doorRatingCd;
    }

    /**
     * Sets the value of the doorRatingCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenEnum }
     *     
     */
    public void setDoorRatingCd(OpenEnum value) {
        this.doorRatingCd = value;
    }

    /**
     * Gets the value of the doorTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link SafeDoorType }
     *     
     */
    public SafeDoorType getDoorTypeCd() {
        return doorTypeCd;
    }

    /**
     * Sets the value of the doorTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SafeDoorType }
     *     
     */
    public void setDoorTypeCd(SafeDoorType value) {
        this.doorTypeCd = value;
    }

    /**
     * Gets the value of the relockingDeviceInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getRelockingDeviceInd() {
        return relockingDeviceInd;
    }

    /**
     * Sets the value of the relockingDeviceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRelockingDeviceInd(Boolean value) {
        this.relockingDeviceInd = value;
    }

    /**
     * Gets the value of the timeLockInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getTimeLockInd() {
        return timeLockInd;
    }

    /**
     * Sets the value of the timeLockInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimeLockInd(Boolean value) {
        this.timeLockInd = value;
    }

    /**
     * Gets the value of the itemDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemDefinitionType2 }
     * 
     * 
     */
    public List<ItemDefinitionType2> getItemDefinition() {
        if (itemDefinition == null) {
            itemDefinition = new ArrayList<ItemDefinitionType2>();
        }
        return this.itemDefinition;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
