//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SuretySvcRs_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuretySvcRs_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}Status" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}RqUID"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SPName" minOccurs="0"/>
 *         &lt;group ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SURETYSVCRS_CHOICE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuretySvcRs_Type", propOrder = {
    "status",
    "rqUID",
    "spName",
    "suretysvcrsmsgs",
    "suretysvcspirsmsgs"
})
public class SuretySvcRsType {

    @XmlElement(name = "Status")
    protected StatusType status;
    @XmlElement(name = "RqUID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rqUID;
    @XmlElement(name = "SPName")
    protected AssignedIdentifier spName;
    @XmlElements({
        @XmlElement(name = "SuretyBondContractAuditRs", type = SuretyBondContractAuditRsType.class),
        @XmlElement(name = "SuretyReportExecutionAddRs", type = SuretyReportExecutionAddRsType.class),
        @XmlElement(name = "SuretyBondPartialImageNotifyReinstateRs", type = SuretyBondPartialImageNotifyReinstateRsType.class),
        @XmlElement(name = "SuretyBondRequestQuoteInqRs", type = SuretyBondRequestQuoteInqRsType.class),
        @XmlElement(name = "SuretyBondPartialImageNotifyCancelRs", type = SuretyBondPartialImageNotifyCancelRsType.class),
        @XmlElement(name = "SuretyBondRenewRs", type = SuretyBondRenewRsType.class),
        @XmlElement(name = "SuretyBondFullImageNotifyRs", type = SuretyBondFullImageNotifyRsType.class),
        @XmlElement(name = "SuretyBondNumberSyncRs", type = SuretyBondNumberSyncRsType.class),
        @XmlElement(name = "SuretyBondRateSyncRs", type = SuretyBondRateSyncRsType.class),
        @XmlElement(name = "SuretyBondInqRs", type = SuretyBondInqRsType.class),
        @XmlElement(name = "SuretyBondPartialImageCancelRs", type = SuretyBondPartialImageCancelRsType.class),
        @XmlElement(name = "SuretyBondRequestAddRs", type = SuretyBondRequestAddRsType.class),
        @XmlElement(name = "SuretyBondPartialImageReinstateRs", type = SuretyBondPartialImageReinstateRsType.class),
        @XmlElement(name = "SuretyBondModRs", type = SuretyBondModRsType.class),
        @XmlElement(name = "SuretyBondSyncStatusRs", type = SuretyBondSyncStatusRsType.class),
        @XmlElement(name = "SuretyBondReissueRs", type = SuretyBondReissueRsType.class),
        @XmlElement(name = "SuretyBondSyncRs", type = SuretyBondSyncRsType.class),
        @XmlElement(name = "SuretyBondBillingSummaryNotifyRs", type = SuretyBondBillingSummaryNotifyRsType.class),
        @XmlElement(name = "SuretyBondFullImageReinstateRs", type = SuretyBondFullImageReinstateRsType.class)
    })
    protected List<Object> suretysvcrsmsgs;
    @XmlElements({
        @XmlElement(name = "SuretyBondReplaceReissueRs", type = SuretyBondReplaceReissueRsType.class),
        @XmlElement(name = "SuretyBondReplaceModRs", type = SuretyBondReplaceModRsType.class),
        @XmlElement(name = "SuretyBondFullImageReplaceReinstateRs", type = SuretyBondFullImageReplaceReinstateRsType.class),
        @XmlElement(name = "SuretyBondUpdateModRs", type = SuretyBondUpdateModRsType.class),
        @XmlElement(name = "SuretyBondReplaceAddRs", type = SuretyBondReplaceAddRsType.class),
        @XmlElement(name = "SuretyBondReplaceRenewRs", type = SuretyBondReplaceRenewRsType.class),
        @XmlElement(name = "SuretyBondRenewListNotifyRs", type = SuretyBondRenewListNotifyRsType.class),
        @XmlElement(name = "SuretyBondUpdateAddRs", type = SuretyBondUpdateAddRsType.class),
        @XmlElement(name = "SuretyBondFullImageUpdateReinstateRs", type = SuretyBondFullImageUpdateReinstateRsType.class),
        @XmlElement(name = "SuretyBondUpdateReissueRs", type = SuretyBondUpdateReissueRsType.class),
        @XmlElement(name = "SuretyBondUpdateRenewRs", type = SuretyBondUpdateRenewRsType.class)
    })
    protected List<Object> suretysvcspirsmsgs;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the rqUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRqUID() {
        return rqUID;
    }

    /**
     * Sets the value of the rqUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRqUID(String value) {
        this.rqUID = value;
    }

    /**
     * Gets the value of the spName property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedIdentifier }
     *     
     */
    public AssignedIdentifier getSPName() {
        return spName;
    }

    /**
     * Sets the value of the spName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedIdentifier }
     *     
     */
    public void setSPName(AssignedIdentifier value) {
        this.spName = value;
    }

    /**
     * Gets the value of the suretysvcrsmsgs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the suretysvcrsmsgs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSURETYSVCRSMSGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuretyBondContractAuditRsType }
     * {@link SuretyReportExecutionAddRsType }
     * {@link SuretyBondPartialImageNotifyReinstateRsType }
     * {@link SuretyBondRequestQuoteInqRsType }
     * {@link SuretyBondPartialImageNotifyCancelRsType }
     * {@link SuretyBondRenewRsType }
     * {@link SuretyBondFullImageNotifyRsType }
     * {@link SuretyBondNumberSyncRsType }
     * {@link SuretyBondRateSyncRsType }
     * {@link SuretyBondInqRsType }
     * {@link SuretyBondPartialImageCancelRsType }
     * {@link SuretyBondRequestAddRsType }
     * {@link SuretyBondPartialImageReinstateRsType }
     * {@link SuretyBondModRsType }
     * {@link SuretyBondSyncStatusRsType }
     * {@link SuretyBondReissueRsType }
     * {@link SuretyBondSyncRsType }
     * {@link SuretyBondBillingSummaryNotifyRsType }
     * {@link SuretyBondFullImageReinstateRsType }
     * 
     * 
     */
    public List<Object> getSURETYSVCRSMSGS() {
        if (suretysvcrsmsgs == null) {
            suretysvcrsmsgs = new ArrayList<Object>();
        }
        return this.suretysvcrsmsgs;
    }

    /**
     * Gets the value of the suretysvcspirsmsgs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the suretysvcspirsmsgs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSURETYSVCSPIRSMSGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuretyBondReplaceReissueRsType }
     * {@link SuretyBondReplaceModRsType }
     * {@link SuretyBondFullImageReplaceReinstateRsType }
     * {@link SuretyBondUpdateModRsType }
     * {@link SuretyBondReplaceAddRsType }
     * {@link SuretyBondReplaceRenewRsType }
     * {@link SuretyBondRenewListNotifyRsType }
     * {@link SuretyBondUpdateAddRsType }
     * {@link SuretyBondFullImageUpdateReinstateRsType }
     * {@link SuretyBondUpdateReissueRsType }
     * {@link SuretyBondUpdateRenewRsType }
     * 
     * 
     */
    public List<Object> getSURETYSVCSPIRSMSGS() {
        if (suretysvcspirsmsgs == null) {
            suretysvcspirsmsgs = new ArrayList<Object>();
        }
        return this.suretysvcspirsmsgs;
    }

}
