//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for WorkCompLossInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkCompLossInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ItemIdInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}JurisdictionCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}JurisdictionDesc" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}WCClaimTypeCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LossConditionTypeCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LossConditionRecoveryTypeCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LossConditionSettlementTypeCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SecondInjuryFundInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}OtherInsuranceInd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}FraudulentClaimCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EmployeeInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EmployerInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CoverageCd" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}VesselCallId" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LossCondition" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}ID" />
 *       &lt;attribute name="SecondInjuryFundRef" type="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkCompLossInfo_Type", propOrder = {
    "itemIdInfo",
    "jurisdictionCd",
    "jurisdictionDesc",
    "wcClaimTypeCd",
    "lossConditionTypeCd",
    "lossConditionRecoveryTypeCd",
    "lossConditionSettlementTypeCd",
    "secondInjuryFundInd",
    "otherInsuranceInd",
    "fraudulentClaimCd",
    "employeeInfo",
    "employerInfo",
    "coverageCd",
    "vesselCallId",
    "lossCondition"
})
public class WorkCompLossInfoType {

    @XmlElement(name = "ItemIdInfo")
    protected ItemIdInfoType itemIdInfo;
    @XmlElement(name = "JurisdictionCd")
    protected OpenEnum jurisdictionCd;
    @XmlElement(name = "JurisdictionDesc")
    protected C100 jurisdictionDesc;
    @XmlElement(name = "WCClaimTypeCd")
    protected WCClaimType wcClaimTypeCd;
    @XmlElement(name = "LossConditionTypeCd")
    protected OpenEnum lossConditionTypeCd;
    @XmlElement(name = "LossConditionRecoveryTypeCd")
    protected OpenEnum lossConditionRecoveryTypeCd;
    @XmlElement(name = "LossConditionSettlementTypeCd")
    protected OpenEnum lossConditionSettlementTypeCd;
    @XmlElement(name = "SecondInjuryFundInd")
    protected Boolean secondInjuryFundInd;
    @XmlElement(name = "OtherInsuranceInd")
    protected Boolean otherInsuranceInd;
    @XmlElement(name = "FraudulentClaimCd")
    protected OpenEnum fraudulentClaimCd;
    @XmlElement(name = "EmployeeInfo")
    protected EmployeeInfoType employeeInfo;
    @XmlElement(name = "EmployerInfo")
    protected EmployerInfoType employerInfo;
    @XmlElement(name = "CoverageCd")
    protected List<Coverages> coverageCd;
    @XmlElement(name = "VesselCallId")
    protected AssignedIdentifier vesselCallId;
    @XmlElement(name = "LossCondition")
    protected LossConditionType lossCondition;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "SecondInjuryFundRef")
    @XmlIDREF
    protected Object secondInjuryFundRef;

    /**
     * Gets the value of the itemIdInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ItemIdInfoType }
     *     
     */
    public ItemIdInfoType getItemIdInfo() {
        return itemIdInfo;
    }

    /**
     * Sets the value of the itemIdInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemIdInfoType }
     *     
     */
    public void setItemIdInfo(ItemIdInfoType value) {
        this.itemIdInfo = value;
    }

    /**
     * Gets the value of the jurisdictionCd property.
     * 
     * @return
     *     possible object is
     *     {@link OpenEnum }
     *     
     */
    public OpenEnum getJurisdictionCd() {
        return jurisdictionCd;
    }

    /**
     * Sets the value of the jurisdictionCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenEnum }
     *     
     */
    public void setJurisdictionCd(OpenEnum value) {
        this.jurisdictionCd = value;
    }

    /**
     * Gets the value of the jurisdictionDesc property.
     * 
     * @return
     *     possible object is
     *     {@link C100 }
     *     
     */
    public C100 getJurisdictionDesc() {
        return jurisdictionDesc;
    }

    /**
     * Sets the value of the jurisdictionDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link C100 }
     *     
     */
    public void setJurisdictionDesc(C100 value) {
        this.jurisdictionDesc = value;
    }

    /**
     * Gets the value of the wcClaimTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link WCClaimType }
     *     
     */
    public WCClaimType getWCClaimTypeCd() {
        return wcClaimTypeCd;
    }

    /**
     * Sets the value of the wcClaimTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link WCClaimType }
     *     
     */
    public void setWCClaimTypeCd(WCClaimType value) {
        this.wcClaimTypeCd = value;
    }

    /**
     * Gets the value of the lossConditionTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link OpenEnum }
     *     
     */
    public OpenEnum getLossConditionTypeCd() {
        return lossConditionTypeCd;
    }

    /**
     * Sets the value of the lossConditionTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenEnum }
     *     
     */
    public void setLossConditionTypeCd(OpenEnum value) {
        this.lossConditionTypeCd = value;
    }

    /**
     * Gets the value of the lossConditionRecoveryTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link OpenEnum }
     *     
     */
    public OpenEnum getLossConditionRecoveryTypeCd() {
        return lossConditionRecoveryTypeCd;
    }

    /**
     * Sets the value of the lossConditionRecoveryTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenEnum }
     *     
     */
    public void setLossConditionRecoveryTypeCd(OpenEnum value) {
        this.lossConditionRecoveryTypeCd = value;
    }

    /**
     * Gets the value of the lossConditionSettlementTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link OpenEnum }
     *     
     */
    public OpenEnum getLossConditionSettlementTypeCd() {
        return lossConditionSettlementTypeCd;
    }

    /**
     * Sets the value of the lossConditionSettlementTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenEnum }
     *     
     */
    public void setLossConditionSettlementTypeCd(OpenEnum value) {
        this.lossConditionSettlementTypeCd = value;
    }

    /**
     * Gets the value of the secondInjuryFundInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSecondInjuryFundInd() {
        return secondInjuryFundInd;
    }

    /**
     * Sets the value of the secondInjuryFundInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSecondInjuryFundInd(Boolean value) {
        this.secondInjuryFundInd = value;
    }

    /**
     * Gets the value of the otherInsuranceInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getOtherInsuranceInd() {
        return otherInsuranceInd;
    }

    /**
     * Sets the value of the otherInsuranceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOtherInsuranceInd(Boolean value) {
        this.otherInsuranceInd = value;
    }

    /**
     * Gets the value of the fraudulentClaimCd property.
     * 
     * @return
     *     possible object is
     *     {@link OpenEnum }
     *     
     */
    public OpenEnum getFraudulentClaimCd() {
        return fraudulentClaimCd;
    }

    /**
     * Sets the value of the fraudulentClaimCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenEnum }
     *     
     */
    public void setFraudulentClaimCd(OpenEnum value) {
        this.fraudulentClaimCd = value;
    }

    /**
     * Gets the value of the employeeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeInfoType }
     *     
     */
    public EmployeeInfoType getEmployeeInfo() {
        return employeeInfo;
    }

    /**
     * Sets the value of the employeeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeInfoType }
     *     
     */
    public void setEmployeeInfo(EmployeeInfoType value) {
        this.employeeInfo = value;
    }

    /**
     * Gets the value of the employerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EmployerInfoType }
     *     
     */
    public EmployerInfoType getEmployerInfo() {
        return employerInfo;
    }

    /**
     * Sets the value of the employerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployerInfoType }
     *     
     */
    public void setEmployerInfo(EmployerInfoType value) {
        this.employerInfo = value;
    }

    /**
     * Gets the value of the coverageCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverageCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverageCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coverages }
     * 
     * 
     */
    public List<Coverages> getCoverageCd() {
        if (coverageCd == null) {
            coverageCd = new ArrayList<Coverages>();
        }
        return this.coverageCd;
    }

    /**
     * Gets the value of the vesselCallId property.
     * 
     * @return
     *     possible object is
     *     {@link AssignedIdentifier }
     *     
     */
    public AssignedIdentifier getVesselCallId() {
        return vesselCallId;
    }

    /**
     * Sets the value of the vesselCallId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignedIdentifier }
     *     
     */
    public void setVesselCallId(AssignedIdentifier value) {
        this.vesselCallId = value;
    }

    /**
     * Gets the value of the lossCondition property.
     * 
     * @return
     *     possible object is
     *     {@link LossConditionType }
     *     
     */
    public LossConditionType getLossCondition() {
        return lossCondition;
    }

    /**
     * Sets the value of the lossCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link LossConditionType }
     *     
     */
    public void setLossCondition(LossConditionType value) {
        this.lossCondition = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the secondInjuryFundRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSecondInjuryFundRef() {
        return secondInjuryFundRef;
    }

    /**
     * Sets the value of the secondInjuryFundRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSecondInjuryFundRef(Object value) {
        this.secondInjuryFundRef = value;
    }

}
