//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:20:12 PM EST 
//


package org.acord.standards.pc_surety.acord1.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkCompLineBusiness_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkCompLineBusiness_Type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}PCLINEBUSINESS">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}WorkCompAssignedRisk" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}WorkCompLossOrPriorPolicy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}WorkCompIndividuals" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}WorkCompRateState" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}IncludeExcludeState" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}CommlCoverage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}EstimatedAnnualRevenuesAmt" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}SubcontractedWorkPct" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}QuestionAnswer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}LegalEntityCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/}OtherCoveredStateProvCd" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkCompLineBusiness_Type", propOrder = {
    "workCompAssignedRisk",
    "workCompLossOrPriorPolicy",
    "workCompIndividuals",
    "workCompRateState",
    "includeExcludeState",
    "commlCoverage",
    "estimatedAnnualRevenuesAmt",
    "subcontractedWorkPct",
    "questionAnswer",
    "legalEntityCd",
    "otherCoveredStateProvCd"
})
public class WorkCompLineBusinessType
    extends PCLINEBUSINESS
{

    @XmlElement(name = "WorkCompAssignedRisk")
    protected WorkCompAssignedRiskType workCompAssignedRisk;
    @XmlElement(name = "WorkCompLossOrPriorPolicy")
    protected List<WorkCompLossOrPriorPolicyType> workCompLossOrPriorPolicy;
    @XmlElement(name = "WorkCompIndividuals")
    protected List<WorkCompIndividualsType> workCompIndividuals;
    @XmlElement(name = "WorkCompRateState", required = true)
    protected List<WorkCompRateStateType> workCompRateState;
    @XmlElement(name = "IncludeExcludeState")
    protected List<IncludeExcludeStateType> includeExcludeState;
    @XmlElement(name = "CommlCoverage")
    protected List<CommlCoverageType> commlCoverage;
    @XmlElement(name = "EstimatedAnnualRevenuesAmt")
    protected CURRENCY estimatedAnnualRevenuesAmt;
    @XmlElement(name = "SubcontractedWorkPct")
    protected PercentLong subcontractedWorkPct;
    @XmlElement(name = "QuestionAnswer")
    protected List<QuestionAnswerType> questionAnswer;
    @XmlElement(name = "LegalEntityCd")
    protected LegalEntity legalEntityCd;
    @XmlElement(name = "OtherCoveredStateProvCd")
    protected List<OpenEnum> otherCoveredStateProvCd;

    /**
     * Gets the value of the workCompAssignedRisk property.
     * 
     * @return
     *     possible object is
     *     {@link WorkCompAssignedRiskType }
     *     
     */
    public WorkCompAssignedRiskType getWorkCompAssignedRisk() {
        return workCompAssignedRisk;
    }

    /**
     * Sets the value of the workCompAssignedRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkCompAssignedRiskType }
     *     
     */
    public void setWorkCompAssignedRisk(WorkCompAssignedRiskType value) {
        this.workCompAssignedRisk = value;
    }

    /**
     * Gets the value of the workCompLossOrPriorPolicy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workCompLossOrPriorPolicy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkCompLossOrPriorPolicy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkCompLossOrPriorPolicyType }
     * 
     * 
     */
    public List<WorkCompLossOrPriorPolicyType> getWorkCompLossOrPriorPolicy() {
        if (workCompLossOrPriorPolicy == null) {
            workCompLossOrPriorPolicy = new ArrayList<WorkCompLossOrPriorPolicyType>();
        }
        return this.workCompLossOrPriorPolicy;
    }

    /**
     * Gets the value of the workCompIndividuals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workCompIndividuals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkCompIndividuals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkCompIndividualsType }
     * 
     * 
     */
    public List<WorkCompIndividualsType> getWorkCompIndividuals() {
        if (workCompIndividuals == null) {
            workCompIndividuals = new ArrayList<WorkCompIndividualsType>();
        }
        return this.workCompIndividuals;
    }

    /**
     * Gets the value of the workCompRateState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workCompRateState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkCompRateState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WorkCompRateStateType }
     * 
     * 
     */
    public List<WorkCompRateStateType> getWorkCompRateState() {
        if (workCompRateState == null) {
            workCompRateState = new ArrayList<WorkCompRateStateType>();
        }
        return this.workCompRateState;
    }

    /**
     * Gets the value of the includeExcludeState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includeExcludeState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludeExcludeState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncludeExcludeStateType }
     * 
     * 
     */
    public List<IncludeExcludeStateType> getIncludeExcludeState() {
        if (includeExcludeState == null) {
            includeExcludeState = new ArrayList<IncludeExcludeStateType>();
        }
        return this.includeExcludeState;
    }

    /**
     * Gets the value of the commlCoverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commlCoverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommlCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommlCoverageType }
     * 
     * 
     */
    public List<CommlCoverageType> getCommlCoverage() {
        if (commlCoverage == null) {
            commlCoverage = new ArrayList<CommlCoverageType>();
        }
        return this.commlCoverage;
    }

    /**
     * Gets the value of the estimatedAnnualRevenuesAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENCY }
     *     
     */
    public CURRENCY getEstimatedAnnualRevenuesAmt() {
        return estimatedAnnualRevenuesAmt;
    }

    /**
     * Sets the value of the estimatedAnnualRevenuesAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENCY }
     *     
     */
    public void setEstimatedAnnualRevenuesAmt(CURRENCY value) {
        this.estimatedAnnualRevenuesAmt = value;
    }

    /**
     * Gets the value of the subcontractedWorkPct property.
     * 
     * @return
     *     possible object is
     *     {@link PercentLong }
     *     
     */
    public PercentLong getSubcontractedWorkPct() {
        return subcontractedWorkPct;
    }

    /**
     * Sets the value of the subcontractedWorkPct property.
     * 
     * @param value
     *     allowed object is
     *     {@link PercentLong }
     *     
     */
    public void setSubcontractedWorkPct(PercentLong value) {
        this.subcontractedWorkPct = value;
    }

    /**
     * Gets the value of the questionAnswer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questionAnswer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestionAnswer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuestionAnswerType }
     * 
     * 
     */
    public List<QuestionAnswerType> getQuestionAnswer() {
        if (questionAnswer == null) {
            questionAnswer = new ArrayList<QuestionAnswerType>();
        }
        return this.questionAnswer;
    }

    /**
     * Gets the value of the legalEntityCd property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntity }
     *     
     */
    public LegalEntity getLegalEntityCd() {
        return legalEntityCd;
    }

    /**
     * Sets the value of the legalEntityCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntity }
     *     
     */
    public void setLegalEntityCd(LegalEntity value) {
        this.legalEntityCd = value;
    }

    /**
     * Gets the value of the otherCoveredStateProvCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherCoveredStateProvCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherCoveredStateProvCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpenEnum }
     * 
     * 
     */
    public List<OpenEnum> getOtherCoveredStateProvCd() {
        if (otherCoveredStateProvCd == null) {
            otherCoveredStateProvCd = new ArrayList<OpenEnum>();
        }
        return this.otherCoveredStateProvCd;
    }

}
